# Generated by Django 5.1.7 on 2025-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
